export const copy = {
  brand: {
    name: 'Talent Orbit',
  },
  nav: {
    home: 'Home',
    assessments: 'Assessments',
    organizations: 'Organizations',
    invites: 'Invites',
    supportCenter: 'Support center',
    settings: 'Settings',
  },
  mobileMenuLabel: 'Open menu',
  notificationsLabel: 'Notifications',
  accountLabel: 'Account',
  list: {
    title: 'Organizations',
    tabs: { owned: 'Owned', participating: 'Participating' },
    newOrganization: 'New organization',
    newOrganizationSubtitle: 'Create a new organization',
    organizations: [
      {
        slug: 'orbit-labs',
        name: 'Orbit Labs',
        badge: 'Owner',
        members: '8 members',
        accent: 'orange',
      },
      {
        slug: 'northstar-team',
        name: 'Northstar Team',
        badge: 'Owner',
        members: '5 members',
        accent: 'sky',
      },
      {
        slug: 'product-guild',
        name: 'Product Guild',
        badge: 'Participating',
        members: '12 members',
        accent: 'violet',
      },
    ],
  },
  create: {
    back: 'Back',
    title: 'Create organization',
    nameLabel: 'Name',
    nameValue: 'Orbit Labs',
    descriptionLabel: 'Description',
    descriptionValue:
      'A place to collaborate, share knowledge, and advance our mission together.',
    ownerLabel: 'Owner',
    ownerValue: 'Team Orbit',
    ownerHint: 'Anonymous identity',
    submit: 'Create organization',
  },
  detail: {
    back: 'Back',
    name: 'Orbit Labs',
    badge: 'Owner',
    moreOptions: 'More options',
    stats: [
      { label: 'Members', value: '8' },
      { label: 'Shared resources', value: '24' },
    ],
    actions: [
      {
        label: 'Knowledge banks',
        description: 'Organize and manage knowledge banks and concepts',
        href: '/knowledge-bank/',
      },
      {
        label: 'Questions',
        description: 'Create and manage questions and question sets',
        href: '/questions-library/',
      },
      {
        label: 'Tests',
        description: 'Build and manage tests to assess knowledge',
        href: '/tests/',
      },
      {
        label: 'Share resource',
        description: 'Share knowledge and files with members',
        href: '/organization-share/',
      },
    ],
  },
  share: {
    back: 'Back',
    title: 'Share resource',
    resourceTypeLabel: 'Resource type',
    resourceTypes: ['Knowledge bank', 'Question', 'Test'],
    resourceLabel: 'Resource',
    resourceValue: 'Frontend Engineering',
    organizationLabel: 'Organization',
    organizationValue: 'Orbit Labs',
    submit: 'Share',
  },
  shared: {
    back: 'Back',
    title: 'Shared resources',
    organization: 'Orbit Labs',
    tabs: { banks: 'Banks', questions: 'Questions', tests: 'Tests' },
    resources: [
      { name: 'Frontend Engineering', teamId: '7f3a9c21', accent: 'orange' },
      { name: 'Data Platform', teamId: 'a8d4e2b7', accent: 'emerald' },
      { name: 'Backend Engineering', teamId: '3c9f1d6e', accent: 'violet' },
    ],
  },
  confirmation: {
    back: 'Back',
    title: 'Sharing confirmation',
    dismiss: 'Dismiss',
    success: 'Shared successfully',
    successSubtitle: 'This resource is now shared with Orbit Labs.',
    resource: { name: 'Frontend Engineering', type: 'Knowledge bank' },
    organizationLabel: 'Organization',
    organizationValue: 'Orbit Labs',
    accessLabel: 'Access',
    accessTitle: 'Shared with members',
    accessSubtitle: 'Members of Orbit Labs can view and use this resource.',
    openResource: 'Open resource',
    stopSharing: 'Stop sharing',
  },
} as const;
