import type { CategoryIconId } from '@/shared/ui/category-icon-ids';

export const ICON_GROUPS = [
  'Jedzenie',
  'Dom',
  'Transport',
  'Zdrowie',
  'Rozrywka',
  'Podróże',
  'Finanse',
  'Dzieci i zwierzęta',
  'Zakupy',
  'Praca i nauka',
] as const;

export type IconGroup = (typeof ICON_GROUPS)[number];

type IconEntry = { label: string; group: IconGroup };

/** Polish label (also the search text) and group for every icon. */
export const ICON_CATALOG: Record<CategoryIconId, IconEntry> = {
  cart: { label: 'Zakupy spożywcze', group: 'Jedzenie' },
  utensils: { label: 'Restauracja', group: 'Jedzenie' },
  coffee: { label: 'Kawa', group: 'Jedzenie' },
  pizza: { label: 'Pizza', group: 'Jedzenie' },
  wine: { label: 'Wino', group: 'Jedzenie' },
  beer: { label: 'Piwo', group: 'Jedzenie' },
  apple: { label: 'Owoce', group: 'Jedzenie' },
  cake: { label: 'Ciasto', group: 'Jedzenie' },
  salad: { label: 'Sałatka', group: 'Jedzenie' },
  croissant: { label: 'Pieczywo', group: 'Jedzenie' },
  icecream: { label: 'Lody', group: 'Jedzenie' },
  soup: { label: 'Zupa', group: 'Jedzenie' },
  fish: { label: 'Ryby', group: 'Jedzenie' },
  sandwich: { label: 'Kanapka', group: 'Jedzenie' },
  home: { label: 'Dom', group: 'Dom' },
  bed: { label: 'Sypialnia', group: 'Dom' },
  sofa: { label: 'Meble', group: 'Dom' },
  shower: { label: 'Łazienka', group: 'Dom' },
  bulb: { label: 'Prąd', group: 'Dom' },
  zap: { label: 'Energia', group: 'Dom' },
  droplet: { label: 'Woda', group: 'Dom' },
  flame: { label: 'Gaz i ogrzewanie', group: 'Dom' },
  wifi: { label: 'Internet', group: 'Dom' },
  wrench: { label: 'Naprawy', group: 'Dom' },
  hammer: { label: 'Remont', group: 'Dom' },
  recycle: { label: 'Śmieci', group: 'Dom' },
  sprout: { label: 'Ogród', group: 'Dom' },
  flower: { label: 'Kwiaty', group: 'Dom' },
  tree: { label: 'Drzewo', group: 'Dom' },
  receipt: { label: 'Rachunki', group: 'Finanse' },
  car: { label: 'Samochód', group: 'Transport' },
  bus: { label: 'Autobus', group: 'Transport' },
  train: { label: 'Pociąg', group: 'Transport' },
  plane: { label: 'Samolot', group: 'Transport' },
  bike: { label: 'Rower', group: 'Transport' },
  fuel: { label: 'Paliwo', group: 'Transport' },
  truck: { label: 'Dostawa', group: 'Transport' },
  ship: { label: 'Prom', group: 'Transport' },
  heart: { label: 'Zdrowie', group: 'Zdrowie' },
  pill: { label: 'Leki', group: 'Zdrowie' },
  stethoscope: { label: 'Lekarz', group: 'Zdrowie' },
  syringe: { label: 'Szczepienie', group: 'Zdrowie' },
  glasses: { label: 'Okulary', group: 'Zdrowie' },
  smile: { label: 'Dentysta', group: 'Zdrowie' },
  bandage: { label: 'Opatrunki', group: 'Zdrowie' },
  dumbbell: { label: 'Siłownia', group: 'Zdrowie' },
  scissors: { label: 'Fryzjer', group: 'Zdrowie' },
  popcorn: { label: 'Rozrywka', group: 'Rozrywka' },
  gamepad: { label: 'Gry', group: 'Rozrywka' },
  music: { label: 'Muzyka', group: 'Rozrywka' },
  film: { label: 'Kino', group: 'Rozrywka' },
  ticket: { label: 'Bilety', group: 'Rozrywka' },
  camera: { label: 'Fotografia', group: 'Rozrywka' },
  theater: { label: 'Teatr', group: 'Rozrywka' },
  headphones: { label: 'Słuchawki', group: 'Rozrywka' },
  tv: { label: 'Telewizja i streaming', group: 'Rozrywka' },
  dices: { label: 'Gry planszowe', group: 'Rozrywka' },
  trophy: { label: 'Sport', group: 'Rozrywka' },
  palette: { label: 'Hobby', group: 'Rozrywka' },
  luggage: { label: 'Bagaż', group: 'Podróże' },
  hotel: { label: 'Hotel', group: 'Podróże' },
  tent: { label: 'Camping', group: 'Podróże' },
  mountain: { label: 'Góry', group: 'Podróże' },
  globe: { label: 'Zagranica', group: 'Podróże' },
  umbrella: { label: 'Wakacje', group: 'Podróże' },
  wallet: { label: 'Portfel', group: 'Finanse' },
  piggy: { label: 'Oszczędności', group: 'Finanse' },
  landmark: { label: 'Bank i urząd', group: 'Finanse' },
  banknote: { label: 'Gotówka', group: 'Finanse' },
  card: { label: 'Karta', group: 'Finanse' },
  coins: { label: 'Wpłaty', group: 'Finanse' },
  percent: { label: 'Podatki i odsetki', group: 'Finanse' },
  shield: { label: 'Ubezpieczenie', group: 'Finanse' },
  repeat: { label: 'Subskrypcje', group: 'Finanse' },
  baby: { label: 'Dziecko', group: 'Dzieci i zwierzęta' },
  dog: { label: 'Pies', group: 'Dzieci i zwierzęta' },
  paw: { label: 'Zwierzęta', group: 'Dzieci i zwierzęta' },
  backpack: { label: 'Szkoła', group: 'Dzieci i zwierzęta' },
  gift: { label: 'Prezenty', group: 'Zakupy' },
  sparkles: { label: 'Inne', group: 'Zakupy' },
  shirt: { label: 'Ubrania', group: 'Zakupy' },
  bag: { label: 'Zakupy', group: 'Zakupy' },
  store: { label: 'Sklep', group: 'Zakupy' },
  gem: { label: 'Biżuteria', group: 'Zakupy' },
  watch: { label: 'Zegarek', group: 'Zakupy' },
  package: { label: 'Paczki', group: 'Zakupy' },
  graduation: { label: 'Edukacja', group: 'Praca i nauka' },
  book: { label: 'Książki', group: 'Praca i nauka' },
  school: { label: 'Szkoła i kursy', group: 'Praca i nauka' },
  pencil: { label: 'Materiały', group: 'Praca i nauka' },
  newspaper: { label: 'Prasa', group: 'Praca i nauka' },
  mail: { label: 'Poczta', group: 'Praca i nauka' },
  phone: { label: 'Telefon', group: 'Praca i nauka' },
  laptop: { label: 'Komputer', group: 'Praca i nauka' },
  briefcase: { label: 'Praca', group: 'Praca i nauka' },
};
