export const copy = {
  title: 'Create your account',
  subtitle: 'Join Talent Orbit in minutes',
  fullNameLabel: 'Full name',
  fullNamePlaceholder: 'Jane Doe',
  emailLabel: 'Email',
  emailPlaceholder: 'you@company.com',
  passwordLabel: 'Password',
  passwordPlaceholder: '••••••••••••',
  showPassword: 'Show',
  confirmPasswordLabel: 'Confirm password',
  confirmPasswordPlaceholder: '••••••••••••',
  agreeToTerms: 'I agree to the Terms and Privacy Policy',
  submit: 'Create account',
  divider: 'or',
  sso: 'Sign up with SSO',
  haveAccount: 'Already have an account?',
  signIn: 'Sign in',
} as const;
