export const copy = {
  brand: {
    name: 'Talent Orbit',
  },
  nav: {
    home: 'Home',
    assessments: 'Assessments',
    invites: 'Invites',
    supportCenter: 'Support center',
    settings: 'Settings',
  },
  mobileMenuLabel: 'Open menu',
  notificationsLabel: 'Notifications',
  accountLabel: 'Account',
  list: {
    title: 'Knowledge Banks',
    subtitle: 'Curated knowledge for better hiring.',
    searchPlaceholder: 'Search banks...',
    filterLabel: 'Filter banks',
    yourBanks: 'Your banks',
    newBank: 'New bank',
    newBankSubtitle: 'Create a new knowledge bank',
    banks: [
      {
        slug: 'frontend-engineering',
        name: 'Frontend Engineering',
        concepts: '42 concepts',
        updated: 'Updated 2 days ago',
        accent: 'orange',
      },
      {
        slug: 'data-platform',
        name: 'Data Platform',
        concepts: '36 concepts',
        updated: 'Updated 5 days ago',
        accent: 'violet',
      },
      {
        slug: 'backend-engineering',
        name: 'Backend Engineering',
        concepts: '28 concepts',
        updated: 'Updated 1 week ago',
        accent: 'sky',
      },
    ],
  },
  create: {
    back: 'Back',
    title: 'Create bank',
    subtitle:
      'Build a new knowledge bank to organize concepts and share knowledge with your team.',
    nameLabel: 'Name',
    namePlaceholder: 'Enter bank name',
    descriptionLabel: 'Description',
    descriptionPlaceholder: "Describe the bank's purpose and scope",
    visibilityLabel: 'Visibility',
    visibilityValue: 'Private',
    ownerLabel: 'Owner',
    ownerValue: 'Team Orbit',
    cancel: 'Cancel',
    submit: 'Create bank',
  },
  detail: {
    back: 'Back',
    name: 'Frontend Engineering',
    moreOptions: 'More options',
    tabs: {
      overview: 'Overview',
      graph: 'Graph',
      concepts: 'Concepts',
    },
    summary: 'Summary',
    stats: [
      { label: 'Concepts', value: '42' },
      { label: 'Linked nodes', value: '128' },
      { label: 'Child banks', value: '4' },
      { label: 'Last updated', value: '2 days ago' },
    ],
    visibility: { label: 'Visibility', value: 'Private' },
    owner: { label: 'Owner', value: 'Team Orbit' },
    rootConcepts: 'Root concepts',
    concepts: [
      { name: 'Web Platform', count: 8 },
      { name: 'React', count: 12 },
      { name: 'Accessibility', count: 6 },
      { name: 'Performance', count: 7 },
    ],
    addConcept: 'Add concept',
  },
  conceptForm: {
    back: 'Back',
    title: 'New concept',
    titleLabel: 'Title',
    titleValue: 'State Management',
    titleMax: 80,
    coverageLabel: 'Coverage',
    coverageValue:
      'Concepts and patterns for managing application state in React applications.',
    coverageMax: 300,
    difficultyLabel: 'Difficulty',
    difficultyValue: 'Intermediate',
    tagsLabel: 'Tags',
    tags: ['React', 'State'],
    tagsHelper: 'Add up to 6 tags to describe this concept.',
    parentLabel: 'Parent concept',
    parentValue: 'React',
    submit: 'Add concept',
  },
} as const;
