import {
  ShoppingCart,
  Car,
  ReceiptText,
  Popcorn,
  Heart,
  Dumbbell,
  Home,
  Gift,
  Sparkles,
  Utensils,
  Coffee,
  Pizza,
  Wine,
  Beer,
  Apple,
  Cake,
  Bus,
  Train,
  Plane,
  Bike,
  Fuel,
  Shirt,
  Baby,
  Dog,
  PawPrint,
  GraduationCap,
  Book,
  Gamepad2,
  Music,
  Film,
  Ticket,
  Camera,
  Smartphone,
  Laptop,
  Wifi,
  Zap,
  Droplets,
  Flame,
  Wrench,
  Hammer,
  Scissors,
  Pill,
  Stethoscope,
  Briefcase,
  Wallet,
  PiggyBank,
  Landmark,
  Umbrella,
  Palette,
  TreeDeciduous,
  Salad,
  Croissant,
  IceCream2,
  Soup,
  Fish,
  Sandwich,
  Bed,
  Sofa,
  ShowerHead,
  Lightbulb,
  Sprout,
  Flower2,
  Globe,
  Hotel,
  Luggage,
  Tent,
  Mountain,
  Banknote,
  CreditCard,
  Theater,
  Headphones,
  Tv,
  Dices,
  Trophy,
  Syringe,
  Glasses,
  Smile,
  Bandage,
  Backpack,
  School,
  Pencil,
  Newspaper,
  Shield,
  Mail,
  Package,
  ShoppingBag,
  Store,
  Gem,
  Watch,
  Truck,
  Ship,
  Recycle,
  Repeat,
  HandCoins,
  Percent,
  type LucideIcon,
} from 'lucide-react';
import { CATEGORY_ICON_IDS, type CategoryIconId } from './category-icon-ids';

export type { CategoryIconId };

const MAP: Record<CategoryIconId, LucideIcon> = {
  cart: ShoppingCart,
  car: Car,
  receipt: ReceiptText,
  popcorn: Popcorn,
  heart: Heart,
  dumbbell: Dumbbell,
  home: Home,
  gift: Gift,
  sparkles: Sparkles,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  wine: Wine,
  beer: Beer,
  apple: Apple,
  cake: Cake,
  bus: Bus,
  train: Train,
  plane: Plane,
  bike: Bike,
  fuel: Fuel,
  shirt: Shirt,
  baby: Baby,
  dog: Dog,
  paw: PawPrint,
  graduation: GraduationCap,
  book: Book,
  gamepad: Gamepad2,
  music: Music,
  film: Film,
  ticket: Ticket,
  camera: Camera,
  phone: Smartphone,
  laptop: Laptop,
  wifi: Wifi,
  zap: Zap,
  droplet: Droplets,
  flame: Flame,
  wrench: Wrench,
  hammer: Hammer,
  scissors: Scissors,
  pill: Pill,
  stethoscope: Stethoscope,
  briefcase: Briefcase,
  wallet: Wallet,
  piggy: PiggyBank,
  landmark: Landmark,
  umbrella: Umbrella,
  palette: Palette,
  tree: TreeDeciduous,
  salad: Salad,
  croissant: Croissant,
  icecream: IceCream2,
  soup: Soup,
  fish: Fish,
  sandwich: Sandwich,
  bed: Bed,
  sofa: Sofa,
  shower: ShowerHead,
  bulb: Lightbulb,
  sprout: Sprout,
  flower: Flower2,
  globe: Globe,
  hotel: Hotel,
  luggage: Luggage,
  tent: Tent,
  mountain: Mountain,
  banknote: Banknote,
  card: CreditCard,
  theater: Theater,
  headphones: Headphones,
  tv: Tv,
  dices: Dices,
  trophy: Trophy,
  syringe: Syringe,
  glasses: Glasses,
  smile: Smile,
  bandage: Bandage,
  backpack: Backpack,
  school: School,
  pencil: Pencil,
  newspaper: Newspaper,
  shield: Shield,
  mail: Mail,
  package: Package,
  bag: ShoppingBag,
  store: Store,
  gem: Gem,
  watch: Watch,
  truck: Truck,
  ship: Ship,
  recycle: Recycle,
  repeat: Repeat,
  coins: HandCoins,
  percent: Percent,
};

type Props = {
  id: CategoryIconId;
  className?: string;
};

export const CategoryIcon = ({ id, className }: Props) => {
  const Cmp = MAP[id] ?? Sparkles;
  return <Cmp className={className} aria-hidden="true" />;
};

export const CATEGORY_ICON_OPTIONS: readonly CategoryIconId[] =
  CATEGORY_ICON_IDS;
