export const copy = {
  brand: {
    name: 'Talent Orbit',
  },
  nav: {
    home: 'Home',
    assessments: 'Assessments',
    questions: 'Questions',
    tests: 'Tests',
    candidates: 'Candidates',
    analytics: 'Analytics',
    users: 'Users',
    knowledgeBank: 'Knowledge Bank',
    reports: 'Reports',
    supportCenter: 'Support center',
    settings: 'Settings',
  },
  mobileMenuLabel: 'Open menu',
  notificationsLabel: 'Notifications',
  accountLabel: 'Account',
  list: {
    title: 'Tests library',
    subtitle: 'Create and manage high-quality tests.',
    searchPlaceholder: 'Search tests...',
    newTest: 'New test',
    tests: [
      {
        name: 'Frontend Core',
        description: 'Core frontend concepts and best practices.',
        questions: 45,
        minutes: 60,
        accent: 'sky',
      },
      {
        name: 'Accessibility Basics',
        description: 'Web accessibility fundamentals and WCAG principles.',
        questions: 30,
        minutes: 40,
        accent: 'violet',
      },
      {
        name: 'React Advanced',
        description: 'Advanced React patterns, performance and architecture.',
        questions: 55,
        minutes: 75,
        accent: 'emerald',
      },
    ],
  },
  name: {
    back: 'Back',
    titleDesktop: 'Name test',
    titleMobile: 'Test details',
    subtitle: 'Provide a name and description for your test.',
    nameLabel: 'Test name',
    name: 'Frontend Core Interview',
    descriptionLabel: 'Description',
    description:
      'A comprehensive assessment of core frontend development concepts including HTML, CSS, JavaScript, and modern best practices.',
    cancel: 'Cancel',
    continue: 'Continue',
  },
  selectQuestions: {
    back: 'Back',
    titleDesktop: 'Select questions',
    titleMobile: 'Add questions',
    subtitle: 'Choose the questions to include in your test.',
    concepts: 'All concepts',
    types: 'All types',
    typeFilters: [
      'All types',
      'Single choice',
      'Multiple choice',
      'Open question',
    ],
    searchPlaceholder: 'Search questions...',
    questionColumn: 'Question',
    conceptTypeColumn: 'Concept / type',
    questions: [
      {
        icon: 'html',
        title: 'HTML Fundamentals',
        question: 'What is HTML and how does it work?',
        concept: 'Web Basics',
        type: 'Single choice',
        checked: true,
      },
      {
        icon: 'js',
        title: 'JavaScript Variables',
        question:
          'Which of the following correctly declares a variable in JavaScript?',
        concept: 'JavaScript',
        type: 'Multiple choice',
        checked: true,
      },
      {
        icon: 'css',
        title: 'CSS Flexbox',
        question: 'How does flexbox align items along the main axis?',
        concept: 'CSS',
        type: 'Single choice',
        checked: true,
      },
      {
        icon: 'react',
        title: 'React Components',
        question: 'What is the purpose of props in React?',
        concept: 'React',
        type: 'Multiple choice',
        checked: false,
      },
    ],
    continue: 'Continue',
  },
  arrange: {
    back: 'Back',
    titleDesktop: 'Arrange & time test',
    titleMobile: 'Arrange & time',
    subtitleDesktop: 'Add questions and set the time for each question.',
    subtitleMobile: 'Drag to reorder questions and set time for each.',
    questionsHeading: 'Questions',
    totalTimeLabel: 'Total time',
    totalMinutes: 10,
    continue: 'Continue',
    questions: [
      {
        icon: 'react',
        question: 'Which hook stores local state?',
        type: 'Single choice',
        minutes: 2,
      },
      {
        icon: 'list',
        question: 'What does useMemo do?',
        type: 'Single choice',
        minutes: 3,
      },
      {
        icon: 'bolt',
        question: 'When does useEffect run?',
        type: 'Single choice',
        minutes: 5,
      },
    ],
  },
  review: {
    back: 'Back',
    title: 'Review test',
    titleMobile: 'Review',
    subtitleDesktop: 'Review your test details and questions.',
    subtitleMobile: 'Review your test before creating.',
    summary: 'Test summary',
    nameLabel: 'Test name',
    name: 'Frontend Core Interview',
    questionsLabel: 'Questions',
    questionsCount: 3,
    totalTimeLabel: 'Total time',
    totalMinutes: 10,
    questionsHeading: 'Questions',
    questionsHeadingOrdered: 'Questions (in order)',
    create: 'Create test',
    questions: [
      { icon: 'react', question: 'Which hook stores local state?', minutes: 2 },
      { icon: 'list', question: 'What does useMemo do?', minutes: 3 },
      { icon: 'bolt', question: 'When does useEffect run?', minutes: 5 },
    ],
  },
  detail: {
    back: 'Back',
    title: 'Test details',
    successBanner: 'Test created successfully',
    successBannerMobile: 'Test created',
    dismiss: 'Dismiss',
    name: 'Frontend Core Interview',
    questionsLabel: 'Questions',
    questionsCount: 3,
    totalTimeLabel: 'Total time',
    totalMinutes: 10,
    ready: 'Ready',
    questionsHeadingOrdered: 'Questions (in order)',
    edit: 'Edit test',
    createExam: 'Create exam',
    questions: [
      { icon: 'react', question: 'Which hook stores local state?', minutes: 2 },
      { icon: 'list', question: 'What does useMemo do?', minutes: 3 },
      { icon: 'bolt', question: 'When does useEffect run?', minutes: 5 },
    ],
  },
} as const;
