export const copy = {
  brand: {
    name: 'Talent Orbit',
  },
  nav: {
    home: 'Home',
    assessments: 'Assessments',
    questions: 'Questions',
    candidates: 'Candidates',
    analytics: 'Analytics',
    supportCenter: 'Support center',
    settings: 'Settings',
  },
  mobileMenuLabel: 'Open menu',
  notificationsLabel: 'Notifications',
  accountLabel: 'Account',
  list: {
    title: 'Questions library',
    subtitle: 'Create and manage high-quality questions.',
    searchPlaceholder: 'Search questions...',
    filterLabel: 'Filter questions',
    newQuestion: 'New question',
    filters: [
      'All types',
      'Single choice',
      'Multiple choice',
      'Open question',
      'Linking',
    ],
    linkedConcept: 'Linked concept',
    questions: [
      {
        title: 'React useState behavior',
        question: "What is React's virtual DOM?",
        typeCode: 'SC',
        typeLabel: 'Single choice',
        accent: 'sky',
        concept: 'React',
      },
      {
        title: 'ARIA roles and semantics',
        question: 'How do you make a web app accessible?',
        typeCode: 'MC',
        typeLabel: 'Multiple choice',
        accent: 'rose',
        concept: 'Accessibility',
      },
      {
        title: 'Rendering optimization',
        question: 'How would you improve rendering performance?',
        typeCode: 'OQ',
        typeLabel: 'Open question',
        accent: 'violet',
        concept: 'Performance',
      },
      {
        title: 'Redux state flow',
        question: 'Which tool manages global state predictably?',
        typeCode: 'LK',
        typeLabel: 'Linking',
        accent: 'emerald',
        concept: 'State Management',
      },
    ],
  },
  linkConcept: {
    back: 'Back',
    title: 'Link concept',
    subtitle: 'Select the concept this question will assess.',
    selectBank: 'Select bank',
    selectConcept: 'Select concept',
    searchPlaceholder: 'Search concepts...',
    bank: 'Frontend Engineering',
    concepts: [
      'Web Platform',
      'React',
      'Accessibility',
      'Performance',
      'State Management',
    ],
    selected: 'React',
    continue: 'Continue',
  },
  chooseType: {
    back: 'Back',
    title: 'Choose type',
    subtitle: 'Select the type of question you want to create.',
    continue: 'Continue',
    types: [
      {
        name: 'singleChoice',
        title: 'Single choice',
        description: 'One correct answer from a list of options.',
      },
      {
        name: 'multipleChoice',
        title: 'Multiple choice',
        description: 'Multiple correct answers from a list of options.',
      },
      {
        name: 'openQuestion',
        title: 'Open question',
        description: 'Answer in free text with no predefined options.',
      },
      {
        name: 'linking',
        title: 'Linking',
        description: 'Link items from one list to another.',
      },
    ],
    selected: 'singleChoice',
  },
  compose: {
    back: 'Back',
    title: 'Compose question',
    conceptLabel: 'Linked concept',
    concept: 'React',
    typeLabel: 'Question type',
    type: 'Single choice',
    questionLabel: 'Question',
    question: 'Which hook stores local state?',
    questionMax: 200,
    optionsLabel: 'Answer options',
    options: [
      { letter: 'A', label: 'useState', correct: true },
      { letter: 'B', label: 'useMemo', correct: false },
      { letter: 'C', label: 'useEffect', correct: false },
      { letter: 'D', label: 'useRef', correct: false },
    ],
    addOption: 'Add option',
    continue: 'Continue',
  },
  review: {
    back: 'Back',
    title: 'Review question',
    summary: 'Summary',
    conceptLabel: 'Concept',
    concept: 'React',
    typeLabel: 'Type',
    type: 'Single choice',
    questionLabel: 'Question',
    question: 'Which hook stores local state?',
    optionsLabel: 'Options',
    options: [
      { letter: 'A', label: 'useState', correct: true },
      { letter: 'B', label: 'useMemo', correct: false },
      { letter: 'C', label: 'useEffect', correct: false },
      { letter: 'D', label: 'useRef', correct: false },
    ],
    correctAnswer: 'Correct answer',
    correct: 'Correct',
    publish: 'Publish question',
  },
  detail: {
    back: 'Back',
    title: 'Question details',
    successBanner: 'Question created successfully',
    dismiss: 'Dismiss',
    questionLabel: 'Question',
    question: 'Which hook stores local state?',
    conceptLabel: 'Linked concept',
    concept: 'React',
    typeLabel: 'Type',
    type: 'Single choice',
    optionsLabel: 'Options and answer',
    options: [
      { letter: 'A', label: 'useState', correct: true },
      { letter: 'B', label: 'useMemo', correct: false },
      { letter: 'C', label: 'useEffect', correct: false },
      { letter: 'D', label: 'useRef', correct: false },
    ],
    correct: 'Correct answer',
    edit: 'Edit question',
    addToTest: 'Add to test',
  },
} as const;
