export const copy = {
  brand: {
    name: 'Talent Orbit',
  },
  nav: {
    home: 'Home',
    assessments: 'Assessments',
    users: 'Users',
    knowledgeBank: 'Knowledge Bank',
    tests: 'Tests',
    reports: 'Reports',
    supportCenter: 'Support center',
    settings: 'Settings',
  },
  thankYou: {
    badge: 'Post-exam',
    title: 'Thank you!',
    subtitle: 'Your attempt is closed.',
    subtitleLine2: "We'll be in touch.",
    exit: 'Exit',
    privacyNote:
      'For your privacy, we do not display scores or share private reports.',
  },
  notes: {
    back: 'Back',
    badge: 'Interviewer / Recruiter',
    titleDesktop: 'Add interview notes',
    titleMobile: 'Add interview notes',
    examLabel: 'Exam',
    exam: 'Frontend Candidate Session',
    candidateIdLabel: 'Candidate ID',
    candidateId: 'CAND-7421',
    notesTitle: 'Interview notes',
    notesHint:
      'Capture key observations, strengths, areas to improve, and next steps.',
    placeholder: 'Start typing your notes here...',
    format: 'Normal',
    strengthsTitle: 'Strengths',
    strengths: [
      'Solid understanding of JavaScript and async flows',
      'Good problem-solving approach',
      'Communicates clearly',
    ],
    concernsTitle: 'Concerns',
    concerns: [
      'Needs more practice with edge cases',
      'Time management under pressure',
    ],
    saveAndContinue: 'Save & continue',
  },
  transcript: {
    back: 'Back',
    badge: 'Interviewer / Recruiter',
    titleDesktop: 'Add transcript',
    titleMobile: 'Add transcript',
    candidateIdLabel: 'Candidate ID',
    candidateId: 'CAND-7421',
    sessionName: 'Frontend Candidate Session',
    sectionTitle: 'Add transcript',
    sectionHint: 'Paste or upload the interview transcript.',
    hintMobile: 'Paste transcript or upload file',
    dropTitleDesktop: 'Paste transcript here',
    dropTitleMobile: 'Drag & drop a file here',
    or: 'or',
    uploadFile: 'Upload file',
    uploadFileMobile: 'or click to upload',
    formats: 'Accepted formats: .txt, .docx, .pdf',
    maxSize: 'Max file size: 20 MB',
    charCount: '0 / 20,000 characters',
    privacyTitle: 'Privacy first:',
    privacyBody:
      'Transcripts are confidential and accessible only to authorized team members involved in the hiring process.',
    privacyBodyMobile: 'Transcripts are private and used only for evaluation.',
    continue: 'Continue',
  },
  review: {
    back: 'Back to exam',
    titleDesktop: 'Review submission',
    titleMobile: 'Review submission',
    subtitle: 'Review your notes and transcript before generating the report.',
    notesTitle: 'Notes',
    notesTitleMobile: 'Interview notes',
    notesSubtitleMobile: 'Your notes from this session',
    notesPreview:
      'The candidate demonstrated strong understanding of component lifecycle, state management, and performance optimization in React.\n\nThey provided clear examples and explained their approach to solving real-world problems.\n\nSuggested improvements in testing strategy and accessibility considerations.',
    notesChars: '1,243 characters',
    transcriptTitle: 'Transcript preview',
    transcriptTitleMobile: 'Transcript',
    transcriptSubtitleMobile: 'Full conversation transcript',
    transcriptPreview:
      'Interviewer: Can you explain the virtual DOM in React?\n\nCandidate: Sure! The virtual DOM is a lightweight JavaScript representation of the real DOM. React uses it to efficiently compare changes and update only the parts that have actually changed.\n\nInterviewer: How does that improve performance?\n\nCandidate: It reduces repaints and reflows in the browser, which makes the UI updates much faster.',
    transcriptChars: '3,856 characters',
    edit: 'Edit',
    privacyNote:
      'Your notes and transcript are stored securely and used only to generate this report. They will not be shared with the candidate.',
    privacyNoteMobile:
      'Your notes and the transcript are private and used only to generate this report.',
    acceptAndGenerate: 'Accept & generate report',
  },
  report: {
    back: 'Back to exam',
    titleMobile: 'Report',
    ready: 'Report ready',
    readySubtitle: 'Your interview report has been generated successfully.',
    candidateLabel: 'Candidate (anonymous)',
    candidateId: 'CAND-7421',
    summaryTitle: 'Summary',
    summary:
      'The candidate demonstrates strong frontend development skills with a solid understanding of React concepts, state management, and performance optimization. They communicate ideas clearly and solve problems methodically. With more focus on testing and accessibility, they can deliver even more robust solutions.',
    summaryMobile:
      'Strong communication and problem-solving mindset. Showed structured thinking and collaboration throughout the session.',
    strengthsTitle: 'Strengths',
    strengths: [
      'Strong understanding of React core concepts',
      'Effective problem solving approach',
      'Clear and structured communication',
      'Performance optimization awareness',
    ],
    strengthsMobile: [
      'Clear communication',
      'Analytical thinking',
      'Ownership & accountability',
      'Collaborative mindset',
    ],
    areasTitle: 'Areas to explore',
    areas: [
      'Testing strategy and coverage',
      'Accessibility best practices',
      'Error handling and edge cases',
      'Deeper knowledge of advanced patterns',
    ],
    areasMobile: [
      'Deeper technical depth',
      'System design trade-offs',
      'Prioritization under ambiguity',
    ],
    exportToWord: 'Export to Word',
    viewDetails: 'View details',
  },
  feedback: {
    back: 'Back to reports',
    titleDesktop: 'Candidate feedback',
    titleMobile: 'Candidate feedback',
    subtitleDesktop: 'Share feedback with the candidate.',
    subtitleMobile: 'Review and share this feedback with the candidate.',
    feedbackLabel: 'Feedback',
    editable: '(editable)',
    edit: 'Edit',
    feedback:
      'Thank you for your time and for sharing your thought process so clearly.\n\nYou have a strong grasp of React fundamentals and demonstrated great problem-solving skills throughout the interview.\n\nTo continue growing, I encourage you to deepen your focus on testing practices and accessibility standards. These will help you build even more reliable and inclusive applications.\n\nKeep up the great work!',
    feedbackMobile:
      'Thank you for your time today. You demonstrated strong analytical thinking and a collaborative approach to problem-solving.\n\nWe encourage you to continue strengthening your technical depth and comfort with system design trade-offs.\n\nWe’ll be in touch soon.',
    charCount: '512 characters',
    copyFeedback: 'Copy feedback',
    copied: 'Copied to clipboard!',
    backToExam: 'Back to exam',
  },
} as const;
