export const DASHBOARD_E2E_IDS = [
  'dashboard:main',
  'dashboard:month-select',
  'dashboard:total',
  'dashboard:change',
  'dashboard:daily-average',
  'dashboard:transactions',
  'dashboard:limit-left',
  'dashboard:expenses',
  'dashboard:summary-error',
  'dashboard:limits',
  'dashboard:limit-total',
  'dashboard:limit-total-amount',
  'dashboard:limit-total-save',
  'dashboard:limit-total-edit',
  'dashboard:limit-total-new',
  'dashboard:limit-list',
  'dashboard:limit-new',
  'dashboard:category-new',
  'dashboard:limit-new-hint',
  'dashboard:limit-form',
  'dashboard:limit-form-category',
  'dashboard:limit-form-amount',
  'dashboard:limit-form-save',
  'dashboard:limit-delete',
  'dashboard:recurring-dialog',
  'dashboard:recurring-detail',
  'dashboard:expense-new',
  'dashboard:new-dialog',
  'dashboard:new-expense-form',
  'dashboard:new-merchant',
  'dashboard:new-amount',
  'dashboard:new-date',
  'dashboard:new-category',
  'dashboard:new-method',
  'dashboard:new-save',
  'dashboard:new-upload',
  'dashboard:new-camera',
  'dashboard:new-manual',
  'dashboard:new-upload-input',
  'dashboard:new-camera-input',
  'dashboard:receipt-cropper',
  'dashboard:receipt-crop-confirm',
  'dashboard:receipt-crop-cancel',
  'dashboard:receipt-scanning',
  'dashboard:receipt-scan-error',
  'dashboard:recurring-form',
  'dashboard:recurring-form-name',
  'dashboard:recurring-form-cost',
  'dashboard:recurring-form-date',
  'dashboard:recurring-form-category',
  'dashboard:recurring-form-method',
  'dashboard:recurring-form-save',
  'dashboard:recurring-delete',
  'dashboard:toast',
  'dashboard:detail',
  'dashboard:edit-merchant',
  'dashboard:edit-amount',
  'dashboard:edit-category',
  'dashboard:save',
  'dashboard:delete',
] as const;

export type DashboardDynamicE2eId =
  | `dashboard:expense:${string | number}`
  | `dashboard:limit-edit:${string | number}`
  | `dashboard:filter:${string | number}`;

export type DashboardE2eId =
  (typeof DASHBOARD_E2E_IDS)[number] | DashboardDynamicE2eId;
