export const copy = {
  brand: {
    name: 'Talent Orbit',
  },
  nav: {
    home: 'Home',
    assessments: 'Assessments',
    users: 'Users',
    knowledgeBank: 'Knowledge Bank',
    tests: 'Tests',
    exams: 'Exams',
    reports: 'Reports',
    supportCenter: 'Support center',
    settings: 'Settings',
  },
  mobileMenuLabel: 'Open menu',
  notificationsLabel: 'Notifications',
  list: {
    title: 'Exams',
    newExam: 'New exam',
    tabs: ['Upcoming', 'Live', 'Closed'],
    exams: [
      {
        icon: 'calendar',
        name: 'Frontend Team Interview',
        date: 'May 28, 2025 · 10:00 AM',
        candidates: 8,
        status: 'Upcoming',
      },
      {
        icon: 'check-blue',
        name: 'React Developer Hiring Test',
        date: 'Jun 4, 2025 · 2:00 PM',
        candidates: 12,
        status: 'Upcoming',
      },
      {
        icon: 'check-green',
        name: 'UI Developer Assessment',
        date: 'Jun 10, 2025 · 11:00 AM',
        candidates: 6,
        status: 'Upcoming',
      },
    ],
  },
  chooseTest: {
    back: 'Back',
    titleDesktop: 'Choose test',
    titleMobile: 'Choose test',
    searchPlaceholder: 'Search tests...',
    continue: 'Continue',
    tests: [
      {
        icon: 'code',
        accent: 'emerald',
        name: 'Frontend Core Interview',
        description:
          'Assess core frontend skills including HTML, CSS, JavaScript, React, and problem solving.',
        questions: 3,
        minutes: 10,
        selected: true,
      },
      {
        icon: 'react',
        accent: 'violet',
        name: 'React Developer Test',
        description:
          'Evaluate React concepts, hooks, state management, and component design.',
        questions: 4,
        minutes: 15,
        selected: false,
      },
      {
        icon: 'js',
        accent: 'blue',
        name: 'JavaScript Essentials',
        description:
          'Test fundamental JavaScript concepts, ES6+ features, and best practices.',
        questions: 3,
        minutes: 10,
        selected: false,
      },
    ],
  },
  configure: {
    back: 'Back',
    titleDesktop: 'Configure exam',
    titleMobile: 'Configure',
    subtitle: 'Set the details for your exam.',
    nameLabel: 'Exam name',
    name: 'Frontend Team Interview',
    setupLabel: 'Setup',
    useDefaultsLabel: 'Use test defaults',
    useDefaultsHint: 'Use the test settings as default.',
    override: 'Override',
    overrideTitle: 'Override settings',
    overrideSubtitle: 'Customize the exam settings if needed.',
    deadlineLabel: 'Deadline (required)',
    deadlineDate: 'May 28, 2025',
    deadlineTime: '10:00 AM',
    closesLabel: 'Closes (required)',
    closesDate: 'May 28, 2025',
    closesTime: '11:00 AM',
    attemptsLabel: 'Attempts',
    attemptsHint: 'Number of attempts allowed per candidate.',
    attempts: 1,
    questionsLabel: 'Questions',
    questionsCount: 3,
    totalTimeLabel: 'Total time',
    totalMinutes: 10,
    passingScoreLabel: 'Passing score',
    passingScore: 60,
    randomizeLabel: 'Randomize questions',
    randomizeValue: 'Off',
    continue: 'Continue',
  },
  share: {
    back: 'Back',
    title: 'Frontend Core Interview',
    titleMobile: 'Exam ready',
    ready: 'Exam ready',
    subtitle: 'You can now share this exam with candidates.',
    successBannerMobile: 'Exam created successfully',
    nameMobile: 'Frontend Candidate Session',
    deadlineLabel: 'Deadline',
    deadline: 'May 31, 2025 11:59 PM',
    summaryTitle: 'Session summary',
    questionsLabel: 'Questions',
    questionsCount: 3,
    durationLabel: 'Duration',
    durationMinutes: 30,
    passScoreLabel: 'Pass score',
    passScore: 70,
    attemptsLabel: 'Attempts allowed',
    attempts: 1,
    attemptsMobile: '1 attempt',
    deadlineFullLabel: 'Deadline',
    deadlineFull: 'May 24, 2025 11:59 PM',
    shareTitle: 'Share exam',
    joinLinkLabel: 'Join link',
    joinLink: 'https://app.talentorbit.com/join/EXM-7K2L',
    joinLinkMobile: 'https://talentorbit.com/exam/abc123',
    passwordLabel: 'Password',
    password: 'orbit2025',
    passwordMobile: 'Z7Q9-LK3P',
    copy: 'Copy',
    start: 'Start accepting participants',
  },
  join: {
    title: 'Join exam',
    subtitle: 'Enter the password to join this exam.',
    anonymous: 'Anonymous',
    linkRecognizedTitle: 'Exam link recognized',
    linkRecognizedName: 'Frontend Candidate Session',
    passwordLabel: 'Password',
    passwordLabelMobile: 'Enter exam password',
    show: 'Show',
    noAccountTitle: 'No account required',
    noAccountBody:
      'You can join and take the exam without creating an account.',
    privateTitle: 'Your identity stays private',
    privateBody: 'Your responses are submitted anonymously.',
    anonymousNoteMobile:
      'You will participate anonymously. No personal information is collected.',
    join: 'Join exam',
    noAccountFooterMobile: 'No account required',
  },
  question: {
    back: 'Back',
    titleMobile: 'Take exam',
    progressLabel: 'Question 1 of 3',
    timer: '29:45',
    timerMobile: '02:00',
    timeRemainingMobile: 'Time remaining',
    question: 'Which hook stores local state?',
    options: [
      { letter: 'A', text: 'useEffect' },
      { letter: 'B', text: 'useState' },
      { letter: 'C', text: 'useContext' },
      { letter: 'D', text: 'useMemo' },
    ],
    optionsMobile: [
      { letter: 'A', text: 'useState' },
      { letter: 'B', text: 'useEffect' },
      { letter: 'C', text: 'useContext' },
      { letter: 'D', text: 'useReducer' },
    ],
    submit: 'Submit answer',
  },
  submitted: {
    title: 'Attempt submitted',
    subtitle: 'This attempt is now closed.',
    idLabel: 'Anonymous attempt ID',
    id: 'TO-EXM-7F2A-K9Q1',
    idMobile: '7F3A-9C21-B8D4',
    done: 'Done',
  },
  detail: {
    back: 'Back',
    title: 'Exam details',
    name: 'Frontend Core Interview',
    nameMobile: 'Frontend Candidate Session',
    statusLabel: 'Status',
    status: 'Closed',
    deadlineLabel: 'Deadline',
    deadline: 'May 20, 2025 · 11:59 PM',
    deadlineMobile: 'May 25, 2025 · 11:59 PM',
    overviewTitle: 'Overview',
    participantsLabel: 'Participants',
    participants: 24,
    completedLabel: 'Completed',
    completed: 21,
    completedPercent: 88,
    averageLabel: 'Average score',
    average: 78,
    shareTitle: 'Share exam credentials',
    shareSubtitle: 'Share the link and access code with participants.',
    linkLabel: 'Exam link',
    link: 'https://app.talentorbit.com/exam/TO-FCI-2025',
    linkMobile: 'https://talentorbit.com/exam/fcs',
    codeLabel: 'Access code',
    code: 'FCI-2025',
    passwordLabelMobile: 'Password',
    codeMobile: 'FCS-2025',
    viewStatistics: 'View statistics',
  },
  statistics: {
    back: 'Back',
    title: 'Statistics',
    participantsLabel: 'Participants',
    participants: 24,
    completedLabel: 'Completed',
    completed: 21,
    averageLabel: 'Average score',
    average: '78%',
    distributionTitle: 'Score distribution',
    distributionDesktop: [
      { label: '0-39%', value: 2 },
      { label: '40-59%', value: 4 },
      { label: '60-79%', value: 8 },
      { label: '80-100%', value: 7 },
    ],
    distributionMobile: [
      { label: '90 - 100%', percent: 29, count: 6, tone: 'emerald' },
      { label: '75 - 89%', percent: 38, count: 8, tone: 'emerald' },
      { label: '50 - 74%', percent: 24, count: 5, tone: 'amber' },
      { label: '0 - 49%', percent: 9, count: 2, tone: 'red' },
    ],
    performanceTitle: 'Question performance',
    questionColumn: 'Question',
    correctColumn: 'Correct %',
    timeColumn: 'Average time',
    performance: [
      {
        question: 'Which hook stores local state?',
        correct: 90,
        time: '1m 45s',
      },
      {
        question: 'Explain the Virtual DOM in React.',
        correct: 76,
        time: '2m 58s',
      },
      {
        question: 'How do you optimize re-rendering in React?',
        correct: 68,
        time: '3m 21s',
      },
    ],
    performanceMobile: [
      { question: 'Which hook stores local state?', percent: 86 },
      { question: 'What does useMemo do?', percent: 71 },
      { question: 'When does useEffect run?', percent: 63 },
    ],
    exportResults: 'Export results',
  },
} as const;
